apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: statsd-exporter

namespace: mastodon
resources:
  - configmap.yaml
  - statsd-exporter.yaml
  - service.yaml
  - servicemonitor.yaml