apiVersion: v1
kind: Service
metadata:
  name: statsd-exporter
  namespace: mastodon
  labels:
    app: statsd-exporter
spec:
  selector:
    app: statsd-exporter
  ports:
  - port: 9102
    targetPort: 9102
    name: statsd1
  - port: 9125
    targetPort: 9125
    protocol: TCP
    name: statsd2
  - port: 9125
    targetPort: 9125
    protocol: UDP
    name: statsd3